[login data]
LoginUsername = YashTech
LoginPassword = YashTech@101


# [registration data]
# RegisterUsername = Demooooooo
# RegisterPassword = Demooooooo@123
# RegisterEmail = demooooooo@cred.in
# RegisterPhone = 7802146596
